"""Generate SVG geometry from the checked-in KOSTAT 2013 subset (no dependencies).

Run from the repository root: python scripts/generate-gyeonggi-map.py
Shared district edges within each city are omitted from the city outline.
No administrative boundaries are drawn by hand.
"""
import collections
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = json.loads((ROOT / 'src/data/gyeonggi-boundaries.geojson').read_text(encoding='utf-8'))
groups = collections.defaultdict(list)
for feature in source['features']:
    groups[feature['properties']['city']].append(feature)

def polygons(feature):
    geometry = feature['geometry']
    return geometry['coordinates'] if geometry['type'] == 'MultiPolygon' else [geometry['coordinates']]

points = [point for features in groups.values() for feature in features
          for polygon in polygons(feature) for ring in polygon for point in ring]
cos_lat = math.cos(math.radians(37.6))
min_x, max_x = min(p[0] for p in points) * cos_lat, max(p[0] for p in points) * cos_lat
min_y, max_y = min(p[1] for p in points), max(p[1] for p in points)
scale = min(320 / (max_x - min_x), 360 / (max_y - min_y))
x_offset = (400 - (max_x - min_x) * scale) / 2
y_offset = (400 - (max_y - min_y) * scale) / 2

def project(point):
    return [(point[0] * cos_lat - min_x) * scale + x_offset,
            (max_y - point[1]) * scale + y_offset]

def xy(point):
    return f'{point[0]:.2f},{point[1]:.2f}'

def inside(point, ring):
    x, y = point
    result = False
    for (ax, ay), (bx, by) in zip(ring, ring[1:]):
        if (ay > y) != (by > y) and x < (bx - ax) * (y - ay) / (by - ay) + ax:
            result = not result
    return result

def segment_distance(point, a, b):
    dx, dy = b[0] - a[0], b[1] - a[1]
    t = max(0, min(1, ((point[0] - a[0]) * dx + (point[1] - a[1]) * dy) / (dx * dx + dy * dy))) if dx or dy else 0
    return math.hypot(point[0] - a[0] - t * dx, point[1] - a[1] - t * dy)

result = []
for name, features in groups.items():
    projected = [[list(map(project, ring)) for ring in polygon] for feature in features for polygon in polygons(feature)]
    edges = collections.Counter()
    for polygon in projected:
        for ring in polygon:
            for a, b in zip(ring, ring[1:]):
                edges[tuple(sorted((tuple(a), tuple(b))))] += 1
    outline = [edge for edge, count in edges.items() if count == 1]
    all_points = [point for polygon in projected for ring in polygon for point in ring]
    # Interior anchor: maximize distance from city outline on a 2px grid.
    # This affects label placement only; it never changes the boundary geometry.
    best, clearance = all_points[0], -1
    for x in range(math.floor(min(p[0] for p in all_points)), math.ceil(max(p[0] for p in all_points)), 2):
        for y in range(math.floor(min(p[1] for p in all_points)), math.ceil(max(p[1] for p in all_points)), 2):
            point = [x, y]
            if not any(inside(point, p[0]) and not any(inside(point, hole) for hole in p[1:]) for p in projected):
                continue
            distance = min(segment_distance(point, a, b) for a, b in outline)
            if distance > clearance:
                best, clearance = point, distance
    result.append({
        'name': name,
        'path': ' '.join('M' + 'L'.join(map(xy, ring[:-1])) + 'Z' for polygon in projected for ring in polygon),
        'outline': ' '.join('M' + xy(a) + 'L' + xy(b) for a, b in outline),
        'anchor': best,
    })
assert len(result) == 31
target = ROOT / 'src/data/gyeonggiMap.ts'
target.write_text('// Generated by scripts/generate-gyeonggi-map.py. Source: KOSTAT 2013; see MAP_SOURCE.md.\n'
                  'export const gyeonggiMap = ' + json.dumps(result, ensure_ascii=False, separators=(',', ':')) + ' as const\n', encoding='utf-8')
print(f'Generated {len(result)} city geometries: {target.name}')
